name: tensorflow
channels:
  - apple
  - conda-forge
dependencies:
    - python=3.10
    - pip>=19.0
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - ipykernel
    - pip:
        - tensorflow==2.12.0
        - tensorflow_addons
        - torch
        - torchvision
        - torchaudio
        - tqdm
        - numba
        - pydot